- name: Generate SSH key for {{ user }}
  user:
    name: "{{ user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Read SSH public key for {{ user }}
  slurp:
    src: "/home/{{ user }}/.ssh/id_rsa.pub"
  register: public_key
- debug: msg="{{ public_key['content'] | b64decode }}"